language: java
jdk: openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DEPLOY_DIR="`pwd`/deploy"
  - secure: YFWiw+LqFlRC4PtkMjXKQqZfVV8IEjPEdgVdkisWAbJOQnyQ8bTRbr1qVVZHmfaXZX3UA9OHrKbpq6EiWpi/gwePQLAyAHxeGW5ori0v2bTVlZnKZPhV+wahA0QG/Va/wrXAwloLyM3nQBWZ3V9EKbN4ru1sNcAGUh9ofhpqRJHwECnUOpQSGjoil7GdYyxJ/tmTW/YeEzJFVq7i3lApvSe5MiGZlhGa0yYDDeZinErJFUxs3xUV6zlygQo5kQ8NMUF10ugCTUvi+Zs5leDh0x+dxuZmul4FMBlF9d41WONW6N5t6XwSCGJLW9KCXfighK9Ote2HoP1ij0+H8Rzl9UBn18gM2shm+7a4U8cRT7v24NVkc1XMUVl2dq8O7OI+uDfp5td1en7xfxJA7+fRsdMVN/HGdxQCXciVlvDnzNnc/4s8ISa54mH2c5nvY/tZ0/qG98upvuBMgA9ykwA/utXISXjXfLYGYB5jMDDHnfVsYNkn+jk0Za2PGBDA8Y76phtXV4j0qPrRwITjjzzGyWjJqP0LPbCEASzfKb9HElFyQmElTmYpi/0rHSHP/nu51d8dlBuDPqPVDxoF6Mz8JRhJoMBeNeUyP2NG4AawyxntAjDXsAblOl91Xp0JAKH0MS87YO80JJigeLRbVJsSq9gCamARhuaAqbnXiXlmz2g=
  - secure: T1cs1sSFtw9ZF73ha2EbME337SB3fykkJkcBVp5kyOU2M4k/il1i9LgeEZN9XqqV3pc3Y+9TVywMEkHw2SkGwN+sWwef3+Jm/MZrFPaDccLl53aZJcGSKbAXJVyNS9ASmtRfhTfgJwMgbdLIOQEWze7JEA8ELbkWvFF0RjdGUfUxBRbDGZGSPMRH3Q0+Z02oLyothWjk20dvG8LnHFIaryKRe6oNmQ2KlzbOl58M72xBQZs5vgnzTDRlyrx/E59VdEaIRccqvQna51srqMz+EqT+uKuoA8mMyWpKdmYa+PCCwBKO8M9V8vETvnBAEhwOfp0Q8d3Ckqm672yZTV6m4Pms+DFmp5lo/y5DMInAojU5Pn/62tnxqghA7QSz8+nZmc6U1ttij9TS/pLFa0ayNe9JMrrDWSbDgCvhwYgmXZdAKqMQYuVJhiZEH/MWdyQxbQn6uOC4rD2nNH2/VjUhVTdgR25aks8Rt9j4zb/nmnamPBdqJnH+JchklzzUp2nqjxkffLtKoX8W1QtZdmN4yZeZk0ZnDVDLAnyLwuy53Gw+TRaDYj9CyU3XJED59CWRcnbVutXQ8DEnM0bkqjV2xO/MVK1I8SGbM3ur3MRedv8uYsOKW8gAENLV+CVH4AYd5OO6IY9H/6UBqtjF4svcVJJeIr+IhwMbEz/C4HXfnqE=

after_success:
- mvn jacoco:report coveralls:report

deploy:
  provider: script
  script: $DEPLOY_DIR/publish.sh
  skip_cleanup: true
  on:
    branch: master
