language: java
jdk: openjdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DEPLOY_DIR="`pwd`/deploy"
  - secure: CWAi3HGRZClYHpicKfyiHI9+mKKiiLDsssw2ZSdfE5924P3TvyvZVR+kih8Xm9CDFfhh49XJuB4bKrdpY5v/GsW7TR0NB7G+rLabqh/m+B1ns/qcFxlDB7tPmlIT6S9Zno18SCAq86l4vaDd+4hiycYYQF3HCat759dZ9I6IL9gi53Zyj0XWrBoi3oOOwYRMMwUqdq5UUT8/ENdcZN6VCsyEOoCaJUb5yPhottrvETGJIcttl7pJ1xkUEvns/Iubs+5dybqOs8gJNoY4s+wGsd4+lO216sr6FWlMrGUsxia9XxFiReQdEF5/GAkyCOc1jg0LR2mLNIcObI4OjKUsZ+qJLFp5BYlnJViA14sTJiQ8QUr0s8cANefF8vZvzOmoCqe7rcTEfmOoewpLBrACTa//x3P0N256oGu3D/k/Y5/UFaMstTcNw7GIIuVBMpX0SORRm05/x52ZkONYyGRo+swJMyTRZIdmdx/S7SNX13Rpa8piNVY7rVUH76MUHsJumOrimkoQFhMsO1epsiOHHU2+6bcZlemCcUXZJ/Imb3o6Or4jcsdyF4ZQEzPEHiKvlmwn6XWHcKuDenqxh1ixjoVpqzGzNC4GGsAkDcbsM33xxEerKwGHcU5T4Fu+H8Esuu8F6BXwN4rhyAqGuwCip7PFixH5b9vEnPbEJjuVf8s=
  - secure: BBpkAp26g/g7d6puMBW/N0NqnDx8Nnnlc082keSv1xqMYWis0P5X6SLt6U6/rCKfEgW5lKndxHd3SBlbnrt87ZknoXye6M/mut3WaLjYeOkerv0Ia2ZVa/NjlZxghWYtU8yU2dlZg6EHAH1xGd0K+8BOQ/zSapg/CxaK9o0lpokbk8Zr6UjOe2un4Qh5jpIs4z3Nw57oLHB5uRXYS3A5TGQukTA2siMLn+bt5HJkZ5Zb2mfXQQgayDm66GEF0s2b2JsfRBJmQDq/UPrg1sjYsqtnqZqHZG7lQcbEVaDVhLbOmQqotFA7QC6x6jc5XwZIFy5r89ESj7PFb0/Jrd54PUawv3XnN7m8XJXM5oZdqQo/Xw4yd0b1a1/sTOYOuG19iE65ei7WsT7luiOlHf49yZHYVkt8XmtbvLnCdsHJqHzVQZWw+DIR+uGLnVVdNT93sNDHTlEtS3X80WsyrS0l+EUK3zhaDlDN6/RbJL5UBg3pZWnArYDEciwBM9VXQ6ic2vxBXsmSdIUklBxaFxAZ7PNST0qhPCHbHRC7BmOhFrKzzp0u8s878xEdj+mnswiYabmH/sMwWa4N1XH0GTemfK5JKO8iS0MduWpvT8fu4LUsdql8z7VCV6hTbqmK8Vd2lXGwIg/35J4XcpnLUeF4oyRoFsSA3gDCghENG9iWCv0=
after_success:
- mvn jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy -P snapshot-release --settings $DEPLOY_DIR/settings.xml -DskipTests=true
  skip_cleanup: true
  on:
    branch: master
